// functions/api/youtube-catalog.js
// POST /api/youtube-catalog — sync the ENTIRE public channel into the learning loop
// GET  /api/youtube-catalog — return the stored catalog
//
// WHY THIS EXISTS
//   youtube-signals.js only measures videos manually marked "published" through the
//   dashboard. That flag records WHICH suggested title was used, so it can only ever
//   cover videos generated by this system. With 1 marked video out of 205, the
//   "channel average" was computed from a single video compared against itself —
//   every title landed in the underperform bucket at 0% vs avg.
//
//   This endpoint reads the channel's full public upload history and derives real
//   title-performance patterns from it. It does NOT touch youtube:published:* or
//   youtube:title:learning — that attribution loop stays exactly as it is.
//
// AGE NORMALISATION
//   Raw view counts are meaningless across a multi-year catalogue: a 2023 video wins
//   by having existed longer. Everything is scored on viewsPerDay against the channel
//   MEDIAN (not mean — one outlier video would otherwise reset the baseline).
//
// Quota: ~11 units per sync (daily limit 10,000).
//
// KV keys written:
//   youtube:channel:catalog — full catalogue + medians + title pattern analysis

const CHANNEL_ID = 'UConuNkzv83jBubkaQpXwXjQ';
const YT_API_BASE = 'https://www.googleapis.com/youtube/v3';

const HEADERS = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': '*',
};

function json(data, status) {
  return new Response(JSON.stringify(data), { status: status || 200, headers: HEADERS });
}

// ── ISO8601 duration → seconds (PT1M30S, PT45S, PT1H2M3S) ─────────────────
function parseDuration(iso) {
  if (!iso) return 0;
  const m = iso.match(/^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/);
  if (!m) return 0;
  return (parseInt(m[1] || 0) * 3600) + (parseInt(m[2] || 0) * 60) + parseInt(m[3] || 0);
}

function median(nums) {
  if (!nums.length) return 0;
  const s = nums.slice().sort(function(a, b) { return a - b; });
  const mid = Math.floor(s.length / 2);
  return s.length % 2 === 0 ? (s[mid - 1] + s[mid]) / 2 : s[mid];
}

// ── Title feature extraction — the patterns we correlate against performance ──
function titleFeatures(title) {
  const t = String(title || '');
  const words = t.trim().split(/\s+/).filter(Boolean);
  // Words in ALL CAPS with 2+ letters (ignores "I", "A", and pure numbers)
  const capsWords = words.filter(function(w) {
    const stripped = w.replace(/[^A-Za-z]/g, '');
    return stripped.length >= 2 && stripped === stripped.toUpperCase();
  });
  return {
    openingWord:  words.length ? words[0].replace(/[^A-Za-z']/g, '').toUpperCase() : null,
    charLength:   t.length,
    wordCount:    words.length,
    hasNumber:    /\d/.test(t),
    hasQuestion:  t.includes('?'),
    hasColon:     t.includes(':'),
    hasParens:    /[(\[]/.test(t),
    hasCaps:      capsWords.length > 0,
    lengthBucket: t.length <= 40 ? 'short (<=40)' : t.length <= 60 ? 'ideal (41-60)' : 'long (>60)',
  };
}

// ── Aggregate one feature across the catalogue ────────────────────────────
// Returns entries with >= minCount samples, sorted by median performance ratio.
function aggregateBy(videos, keyFn, minCount) {
  const buckets = {};
  videos.forEach(function(v) {
    const key = keyFn(v);
    if (key === null || key === undefined || key === '') return;
    if (!buckets[key]) buckets[key] = [];
    buckets[key].push(v.performanceRatio);
  });
  return Object.keys(buckets)
    .filter(function(k) { return buckets[k].length >= (minCount || 3); })
    .map(function(k) {
      return {
        value:      k,
        count:      buckets[k].length,
        medianPerf: Math.round(median(buckets[k]) * 100) / 100,
      };
    })
    .sort(function(a, b) { return b.medianPerf - a.medianPerf; });
}

// ── GET — return stored catalogue ─────────────────────────────────────────
export async function onRequestGet(context) {
  try {
    const catalog = await context.env.FFX_KV
      .get('youtube:channel:catalog', { type: 'json' })
      .catch(function() { return null; });
    return json({ catalog: catalog || null });
  } catch(err) {
    return json({ error: err.message }, 500);
  }
}

// ── POST — rebuild the catalogue from the YouTube Data API ────────────────
export async function onRequestPost(context) {
  const env = context.env;

  if (!env.YOUTUBE_API_KEY) {
    return json({
      error: 'YOUTUBE_API_KEY not set in Cloudflare Pages environment variables.',
    }, 500);
  }
  if (!env.FFX_KV) return json({ error: 'FFX_KV binding not found' }, 500);

  try {
    // ── Step 1: resolve the uploads playlist ────────────────────────────
    let uploadsPlaylistId = null;
    const chRes = await fetch(
      YT_API_BASE + '/channels?part=contentDetails&id=' + CHANNEL_ID + '&key=' + env.YOUTUBE_API_KEY
    );
    if (chRes.ok) {
      const chData = await chRes.json();
      const item = chData.items && chData.items[0];
      uploadsPlaylistId = item
        && item.contentDetails
        && item.contentDetails.relatedPlaylists
        && item.contentDetails.relatedPlaylists.uploads;
    }
    // Fallback: uploads playlist is the channel ID with the UC prefix swapped for UU
    if (!uploadsPlaylistId) uploadsPlaylistId = 'UU' + CHANNEL_ID.slice(2);

    // ── Step 2: page through every upload ───────────────────────────────
    const videoIds = [];
    let pageToken = '';
    for (let page = 0; page < 40; page++) { // hard stop at 2000 videos
      const url = YT_API_BASE + '/playlistItems?part=contentDetails&maxResults=50'
        + '&playlistId=' + encodeURIComponent(uploadsPlaylistId)
        + (pageToken ? '&pageToken=' + pageToken : '')
        + '&key=' + env.YOUTUBE_API_KEY;
      const res = await fetch(url);
      if (!res.ok) {
        const errText = await res.text();
        throw new Error('playlistItems.list failed: ' + res.status + ' ' + errText);
      }
      const data = await res.json();
      (data.items || []).forEach(function(it) {
        if (it.contentDetails && it.contentDetails.videoId) videoIds.push(it.contentDetails.videoId);
      });
      pageToken = data.nextPageToken || '';
      if (!pageToken) break;
    }

    if (!videoIds.length) {
      return json({ error: 'No videos found on channel ' + CHANNEL_ID }, 404);
    }

    // ── Step 3: fetch stats in batches of 50 ────────────────────────────
    const now = Date.now();
    const videos = [];
    for (let i = 0; i < videoIds.length; i += 50) {
      const batch = videoIds.slice(i, i + 50);
      const res = await fetch(
        YT_API_BASE + '/videos?part=snippet,statistics,contentDetails&id=' + batch.join(',')
        + '&key=' + env.YOUTUBE_API_KEY
      );
      if (!res.ok) {
        const errText = await res.text();
        throw new Error('videos.list failed: ' + res.status + ' ' + errText);
      }
      const data = await res.json();
      (data.items || []).forEach(function(item) {
        const publishedAt   = item.snippet.publishedAt;
        const ageDays       = Math.max(1, (now - new Date(publishedAt).getTime()) / 86400000);
        const viewCount     = parseInt(item.statistics.viewCount || 0);
        const likeCount     = parseInt(item.statistics.likeCount || 0);
        const commentCount  = parseInt(item.statistics.commentCount || 0);
        const durationSec   = parseDuration(item.contentDetails && item.contentDetails.duration);
        videos.push({
          videoId:        item.id,
          title:          item.snippet.title || '',
          publishedAt:    publishedAt,
          ageDays:        Math.round(ageDays),
          durationSec:    durationSec,
          isShort:        durationSec > 0 && durationSec <= 60,
          viewCount:      viewCount,
          likeCount:      likeCount,
          commentCount:   commentCount,
          viewsPerDay:    Math.round((viewCount / ageDays) * 100) / 100,
          engagementRate: viewCount > 0
            ? Math.round(((likeCount + commentCount) / viewCount) * 10000) / 100
            : 0,
        });
      });
    }

    // ── Step 4: baseline from mature long-form videos only ──────────────
    // Shorts have entirely different view dynamics and would distort long-form
    // title learning. Videos under 7 days old are too fresh to judge.
    const longForm = videos.filter(function(v) { return !v.isShort; });
    const mature   = longForm.filter(function(v) { return v.ageDays >= 7; });
    const baseline = mature.length >= 5 ? mature : longForm;
    const medianViewsPerDay = median(baseline.map(function(v) { return v.viewsPerDay; }));

    // performanceRatio: 1.0 = exactly the channel median, 2.0 = double it
    videos.forEach(function(v) {
      v.performanceRatio = medianViewsPerDay > 0
        ? Math.round((v.viewsPerDay / medianViewsPerDay) * 100) / 100
        : 0;
      v.tier = v.performanceRatio >= 1.5 ? 'top'
             : v.performanceRatio >= 1.0 ? 'above'
             : v.performanceRatio >= 0.5 ? 'below'
             : 'bottom';
    });

    // ── Step 5: correlate title features with performance ───────────────
    // Only mature long-form videos inform title patterns.
    const scored = videos.filter(function(v) { return !v.isShort && v.ageDays >= 7; });
    scored.forEach(function(v) { v.features = titleFeatures(v.title); });

    const byPerf = scored.slice().sort(function(a, b) { return b.performanceRatio - a.performanceRatio; });

    const catalog = {
      fetchedAt:          new Date().toISOString(),
      channelId:          CHANNEL_ID,
      totalVideos:        videos.length,
      longFormCount:      longForm.length,
      shortsCount:        videos.length - longForm.length,
      scoredCount:        scored.length,
      medianViewsPerDay:  Math.round(medianViewsPerDay * 100) / 100,
      medianViews:        Math.round(median(baseline.map(function(v) { return v.viewCount; }))),

      // The prompt reads these two lists directly
      topPerformers: byPerf.slice(0, 12).map(function(v) {
        return {
          title: v.title, videoId: v.videoId, viewCount: v.viewCount,
          viewsPerDay: v.viewsPerDay, performanceRatio: v.performanceRatio,
          engagementRate: v.engagementRate, ageDays: v.ageDays,
        };
      }),
      bottomPerformers: byPerf.slice(-8).reverse().map(function(v) {
        return {
          title: v.title, videoId: v.videoId, viewCount: v.viewCount,
          viewsPerDay: v.viewsPerDay, performanceRatio: v.performanceRatio,
          ageDays: v.ageDays,
        };
      }),

      patterns: {
        openingWord:  aggregateBy(scored, function(v) { return v.features.openingWord; }, 3),
        lengthBucket: aggregateBy(scored, function(v) { return v.features.lengthBucket; }, 3),
        hasNumber:    aggregateBy(scored, function(v) { return v.features.hasNumber ? 'with number' : 'no number'; }, 3),
        hasQuestion:  aggregateBy(scored, function(v) { return v.features.hasQuestion ? 'question form' : 'statement form'; }, 3),
        hasColon:     aggregateBy(scored, function(v) { return v.features.hasColon ? 'colon split' : 'no colon'; }, 3),
        hasCaps:      aggregateBy(scored, function(v) { return v.features.hasCaps ? 'ALL-CAPS word' : 'no caps word'; }, 3),
      },
    };

    await env.FFX_KV.put('youtube:channel:catalog', JSON.stringify(catalog));
    console.log('[youtube-catalog] Synced', videos.length, 'videos |',
      scored.length, 'scored | median vpd:', catalog.medianViewsPerDay);

    return json({ success: true, catalog: catalog });

  } catch(err) {
    console.error('[youtube-catalog] Error:', err.message);
    return json({ error: err.message }, 500);
  }
}

export async function onRequestOptions() {
  return new Response(null, { status: 204, headers: {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  }});
}
